### PR TITLE
Babel, tests, refactored

### PR DESCRIPTION
**Pull request by AntonBryansky**

### CODE REVIEW

**Comment by ichi404gh** [comment]
- `bot` is still not defined in index.js
- change `src/filter.js` reference to `src/filters.js` in `test.js`
- ignore `build/` directory
- ignore `config.json`, create `config.example.js`


Include new filter and menu buttons that I recently added.

I not sure about we need to even use babel for node project, because modern node have most of es6 features (except ts-like imports e.g., but this is unnecessary). I'm open to discus, but I think we don't need it.

**Comment by AntonBryansky** [comment]
Fixed.
Not all work properly at last version node (8.4.0). Function "import" offten throw error.

**Comment by ichi404gh** [comment]
What isn't work properly?
Use 'requre' instead of 'import'.

**Comment by AntonBryansky** [comment]
Replaced by 'require'. Babel deleted.

**Pull request merged**
